name: nounmobilelibrary
description: "Mobile Library Application for NOUN Computer Science Students"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase Services
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  firebase_storage: ^13.0.3
  firebase_auth: ^6.1.1
  
  # Local Database
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # PDF Viewing
  flutter_pdfview: ^1.3.3
  
  # HTTP & File Downloads
  dio: ^5.8.1
  
  # UI & Icons
  lucide_icons_flutter: ^3.1.5
  
  # State Management
  provider: ^6.1.2
  
  # Connectivity Check
  connectivity_plus: ^7.0.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # UI Utilities
  intl: ^0.20.2
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/
    - assets/courses/100_level/
    - assets/courses/200_level/
    - assets/courses/300_level/
    - assets/courses/400_level/
  
  